apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  labels:
    app: mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - name: mlops-container
          image: mlops:latest
          ports:
            - containerPort: 80 
          env:
            - name: ENV_VAR_NAME
